# Generated by Django 4.1.5 on 2023-02-17 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'Посты', 'verbose_name_plural': 'Посты'},
        ),
    ]
